### ISSUE TITLE
Convert to an extension supporting Blender 4.2 (LTS)

### ISSUE THREAD

**Issue by giovannipizzi** [beautiful-atoms/beautiful-atoms#214]
Blender 4.2 (LTS) has just been released. This replaces legacy add-ons with extensions, that are much more powerful. Among other things, the most relevant I think (that is the only thing that I didn't like of beautiful-atoms) is that one can now provide wheels for the dependencies. So, probably now there is no need anymore of very complex installation procedures!
One can just package the wheels in a package zip, and just dragging the zip file on the blender window installs it.

I therefore suggest to convert this add-on to an extension.

[Instructions to create an extension](https://docs.blender.org/manual/en/latest/advanced/extensions/index.html)

Indeed, I tried to create an empty extension to verify that one can install the dependencies `ase` and `scikit-image`, creating a requirements.txt file with
```
ase==3.23.0
scikit-image==0.24.0
```

I then downloaded the wheels with the command `pip wheel -w ./wheels -r requirements.txt`
And the `blender_manifest.toml` is finally this (note that the list of wheels is specific to my archictecture):
```toml
schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "batoms"
version = "3.0.0"
name = "Beautiful Atoms"
tagline = "Creating and editing atoms, crystals and molecular structures"
maintainer = "Beautiful Atoms team <xing.wang@gmail.com>"
# Supported types: "add-on", "theme"
type = "add-on"

# Optional link to documentation, support, source files, etc
website = "https://github.com/beautiful-atoms/beautiful-atoms"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["Import-Export", "Modeling"]

blender_version_min = "4.2.0"
# # Optional: Blender version that the extension does not support, earlier versions are supported.
# # This can be omitted and defined later on the extensions platform if an issue is found.
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-only",
]
# Optional: required by some licenses.
# copyright = [
#   "2002-2024 Developer Name",
#   "1998 Company Name",
# ]

# Optional list of supported platforms. If omitted, the extension will be available in all operating systems.
# platforms = ["windows-x64", "macos-arm64", "linux-x64"]
# Other supported platforms: "windows-arm64", "macos-x64"

# Optional: bundle 3rd party Python modules.
# https://docs.blender.org/manual/en/dev/advanced/extensions/python_wheels.html
wheels = [
  "./wheels/python_dateutil-2.9.0.post0-py2.py3-none-any.whl",
  "./wheels/pillow-10.4.0-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/scikit_image-0.24.0-cp311-cp311-macosx_12_0_arm64.whl",
  "./wheels/fonttools-4.53.1-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/numpy-2.0.0-cp311-cp311-macosx_14_0_arm64.whl",
  "./wheels/kiwisolver-1.4.5-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/imageio-2.34.2-py3-none-any.whl",
  "./wheels/pyparsing-3.1.2-py3-none-any.whl",
  "./wheels/matplotlib-3.9.1-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/cycler-0.12.1-py3-none-any.whl",
  "./wheels/ase-3.23.0-py3-none-any.whl",
  "./wheels/six-1.16.0-py2.py3-none-any.whl",
  "./wheels/packaging-24.1-py3-none-any.whl",
  "./wheels/lazy_loader-0.4-py3-none-any.whl",
  "./wheels/networkx-3.3-py3-none-any.whl",
  "./wheels/contourpy-1.2.1-cp311-cp311-macosx_11_0_arm64.whl",
  "./wheels/tifffile-2024.7.2-py3-none-any.whl",
  "./wheels/scipy-1.14.0-cp311-cp311-macosx_14_0_arm64.whl",
]

# # Optional: add-ons can list which resources they will require:
# # * files (for access of any filesystem operations)
# # * network (for internet access)
# # * clipboard (to read and/or write the system clipboard)
# # * camera (to capture photos and videos)
# # * microphone (to capture audio)
# #
# # If using network, remember to also check `bpy.app.online_access`
# # https://docs.blender.org/manual/en/dev/advanced/extensions/addons.html#internet-access
# #
# # For each permission it is important to also specify the reason why it is required.
# # Keep this a single short sentence without a period (.) at the end.
# # For longer explanations use the documentation or detail page.
#
[permissions]
network = "Optionally get crystal structures and molecules from internet"
files = "Import/export crystal structure files from/to disk"
# clipboard = "Copy and paste bone transforms"

# Optional: build settings.
# https://docs.blender.org/manual/en/dev/advanced/extensions/command_line_arguments.html#command-line-args-extension-build
# [build]
# paths_exclude_pattern = [
#   "__pycache__/",
#   "/.git/",
#   "/*.zip",
# ]
```

Finally, creating the extension by running, in the folder, `blender --command extension build` creates a `batoms-3.0.0.zip` file. If I drag it in blender and install it, I can now run `import ase` and `import skimage` in the blender python console, and it works!

[Note: even uninstalling the extension keeps the packages installed. I think therefore that this works like a virtual environment. I think there might be clashes of versions of dependencies between packages.. not sure how blender will manage them, I guess we will see this in the future].

If the conversion is done, this can be done following the [instructions to convert from legacy add-ons to extensions](https://docs.blender.org/manual/en/latest/advanced/extensions/addons.html#converting-a-legacy-add-on-into-an-extension).

A few tasks that I think are needed, in a first version (following also in part what's written in the docs linked above):

- [ ] create a 'create-extension.sh' script that runs the `pip wheel` command, then checks the files (that are architecture specific) and creates the correct manifest TOML file, and finally builds into a zip. (In the future: one could create the zip automatically with GitHub actions, for all architectures (see also notes [on the docs](https://docs.blender.org/manual/en/latest/advanced/extensions/python_wheels.html#how-to-bundle-wheels) on multiple architectures). However I guess that soon someone will write a GitHub action to automate this.
- [ ] Remove the bl_info information (this is now in the manifest).
- [ ] Replace all references to the module name to __package__.
- [ ] Make all module imports to use relative import (see notes in the docs above)
- [ ] Check that in the class subclassing from `bpy.types.AddonPreferences`, `bl_idname = __package__` and not `= "atoms"`
- [ ] change any `bpy.context.preferences.addons["batoms"]` to `bpy.context.preferences.addons[__package__]`

Note from the docs, they suggest to use e.g. the syntax `from .. import __package__ as base_package`. One could then probably add as a first line `from .. import __package__ as batoms` specifically, and then the rest of the imports would work? (Of course the import should be adapted depending on how deep the folder structure is, e.g. `from ... import __package__ as base_package` if it's two levels deep etc). However, I didn't try this.

Once this is done, if all works, I would personally suggest to 
- release a major release supporting only Blender 4.2, and say in the readme that for older versions one should use version 2.3 of Beautiful Atoms
- remove any old code and docs and discussion on how to custom replace python, use conda, etc
- replace the docker images with the [new feature of blender to create a portable installation](https://docs.blender.org/manual/en/4.2/advanced/blender_directory_layout.html#portable-installation) by just creating a `portable` folder next to the portable executable
and (as I mentioned above) in the mid term, automate the creation of the zip for the most relevant platforms (I would check those supported by blender, probably Windows, Linux, Mac (and at least for Mac both x86 and arm64, possibly also for the others?)
